version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "product-events:1:1,user-events:1:1,policy-events:1:1,payment-events:1:1"
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongodb-init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - KAFKA_BROKERS=kafka:9093
      - PRODUCT_SERVICE_URL=http://product-service:3001
      - USER_SERVICE_URL=http://user-service:3002
      - POLICY_SERVICE_URL=http://policy-service:3003
      - PAYMENT_SERVICE_URL=http://payment-service:3004
    depends_on:
      - kafka
      - product-service
      - user-service
      - policy-service
      - payment-service

  product-service:
    build: ./product-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGODB_URI=mongodb://mongodb:27017/health_insurance
      - KAFKA_BROKERS=kafka:9093
    depends_on:
      - kafka
      - mongodb

  user-service:
    build: ./user-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - MONGODB_URI=mongodb://mongodb:27017/health_insurance
      - KAFKA_BROKERS=kafka:9093
    depends_on:
      - kafka
      - mongodb

  policy-service:
    build: ./policy-service
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - MONGODB_URI=mongodb://mongodb:27017/health_insurance
      - KAFKA_BROKERS=kafka:9093
    depends_on:
      - kafka
      - mongodb

  payment-service:
    build: ./payment-service
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
      - MONGODB_URI=mongodb://mongodb:27017/health_insurance
      - KAFKA_BROKERS=kafka:9093
    depends_on:
      - kafka
      - mongodb

volumes:
  mongodb_data:
